const SAVE_KEY='idol_dynasty_v07_save';
const $=s=>document.querySelector(s); const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a; const pick=a=>a[rand(0,a.length-1)]; const money=n=>'¥'+Math.round(n).toLocaleString('ja-JP'); const avg=a=>a.reduce((x,y)=>x+y,0)/Math.max(1,a.length);
const PORTRAITS=Array.from({length:8},(_,i)=>`assets/char_${i+1}.png`);
const NAMES=['羽音','凛','美月','ひより','七海','彩花','玲奈','心春','美羽','紗良','莉央','茉白','澪','琴音','乃愛','陽菜','柚葉','咲良','愛梨','杏奈','瑠花','翠','詩乃','真白'];
const TRAITS=['努力家','天才肌','負けず嫌い','天然','ファンサ職人','SNS強者','リーダー型','表現者','研究熱心','ムードメーカー'];
const COLORS=[['スカイブルー','#6bcffa'],['ピンク','#ff91bf'],['ラベンダー','#b8a2ff'],['ミント','#70dbbd'],['レモン','#ffd96d'],['レッド','#ff7f90'],['ネイビー','#5e81a6'],['ホワイト','#e8f4fb']];
const CONCEPTS=[['seiso','王道清楚','正統派。ライブとファン満足が安定。'],['dreamy','儚い青春','物語性と女性人気が伸びやすい。'],['cute','かわいい','SNSと特典会が強い。'],['cool','クール','ブランドとダンス映え。'],['rock','ロック','ライブ熱量が伸びやすい。']];
const OUTFITS=[['制服','清楚で初期コストが低い'],['フリル','王道アイドル感が高い'],['プリンセス','豪華。ブランド向け'],['ストリート','ダンス・SNS向け'],['幻想','儚い楽曲に強い'],['ロック','ライブ熱量向け']];
const ACTIONS=[
 {id:'lesson',icon:'🎧',name:'集中レッスン',cost:90000,desc:'歌・ダンス・ステージを伸ばす',impact:'実力＋ / 疲労＋'},
 {id:'sns',icon:'📱',name:'SNS週間',cost:30000,desc:'自撮り・ショート動画・配信',impact:'話題＋ / 新規ファン＋'},
 {id:'street',icon:'🎤',name:'対バン・路上ライブ',cost:70000,desc:'現場経験を積んで濃いファンを作る',impact:'ライブ力＋ / ファン＋'},
 {id:'fan',icon:'🤝',name:'特典会',cost:50000,desc:'既存ファンとの距離を縮める',impact:'ファン信頼＋ / 収益＋'},
 {id:'media',icon:'📺',name:'メディア営業',cost:120000,desc:'番組・雑誌・案件を狙う',impact:'認知＋ / ブランド＋'},
 {id:'rest',icon:'🫧',name:'休養と制作会議',cost:20000,desc:'疲労を抜きながら次の企画を練る',impact:'疲労− / ムード＋'}
];
const VENUES=[
 {id:'50',name:'地下ライブハウス',cap:50,cost:70000,ticket:2500,power:0},
 {id:'100',name:'100人ライブハウス',cap:100,cost:110000,ticket:3000,power:8},
 {id:'300',name:'300人ライブハウス',cap:300,cost:190000,ticket:3500,power:18},
 {id:'800',name:'800人ホール',cap:800,cost:450000,ticket:4500,power:30},
 {id:'2000',name:'Zepp級',cap:2000,cost:950000,ticket:5500,power:44},
 {id:'10000',name:'武道館級',cap:10000,cost:3900000,ticket:7800,power:62}
];
const SONG_TITLES=['透明なサイダー','君だけのスター','青空センチメント','瞬間シャッター','夏色メモリー','月の向こう側','恋する境界線','未完成シグナル','Sparkle Days','放課後パレット','星屑リフレイン','僕らのプロローグ'];
const RIVAL_NAMES=['LUMINA','MELTY HOUR','NOIR PARADE','CANDY LOOP','ASTER','NEON RIOT'];
let setup={agency:'LUMIERE PRODUCTION',group:'ASTERIA',concept:'seiso',logoColor:'#6bcffa',logoMark:'✦',outfit:'制服'};
let selectSet=new Set(); let state=null; let toastTimer=null;

function memberScore(m){return Math.round(avg([m.stats.vocal,m.stats.dance,m.stats.visual,m.stats.talk,m.stats.sns,m.stats.stage])*.72+m.star*.28)}
function power(){const ms=activeMembers(); if(!ms.length)return 1; return clamp(Math.round(avg(ms.map(memberScore))*.64+Math.log10(state.fans+10)*9+state.brand*.18+state.livePower*.16),1,100)}
function tier(p=power()){return p>=90?'S+':p>=80?'S':p>=70?'A+':p>=60?'A':p>=50?'B+':p>=40?'B':p>=30?'C':p>=20?'D':'E'}
function freshMember(i){const [colorName,color]=COLORS[i%COLORS.length];return {id:'m'+Date.now()+i+rand(1,9999),name:pick(NAMES.filter(n=>!state?.members?.some(m=>m.name===n))),age:rand(16,21),portrait:PORTRAITS[i%PORTRAITS.length],trait:pick(TRAITS),colorName,color,stats:{vocal:rand(38,78),dance:rand(38,80),visual:rand(45,86),talk:rand(30,74),sns:rand(30,82),stage:rand(35,78)},star:rand(45,94),potential:rand(55,98),popularity:rand(40,180),mood:rand(68,90),fatigue:rand(4,20),ambition:rand(35,90),bond:60,status:'active',storyLevel:0,storyLog:[]}}
function activeMembers(){return state.members.filter(m=>m.status==='active')}
function center(){return state.members.find(m=>m.id===state.centerId)||activeMembers()[0]}
function freshState(){return {screen:'title',tab:'home',year:1,month:1,agency:'',group:'',concept:'seiso',logoColor:'#6bcffa',logoMark:'✦',outfit:'制服',cash:3000000,fans:0,brand:8,trust:70,livePower:8,buzz:5,members:[],centerId:null,selectedIds:[],songs:[],activeSongId:null,news:[],history:[],rivals:RIVAL_NAMES.map((n,i)=>({name:n,power:rand(18,43)+i*2,growth:rand(-2,8),fans:rand(900,8000)})),objective:null,objectiveCount:0,selectedAction:null,staff:{manager:false,trainer:false,sns:false,creative:false},monthlyFixed:90000,lastMonth:null,pendingEvent:null,modalMemberId:null,livePlan:{venueId:'100',setlist:[],posterTheme:'sky'},liveRun:null,awardLog:[],snsPosts:[],companyRep:10,label:'自主制作',generation:1,secondGen:false}}
function showToast(t){document.querySelectorAll('.toast').forEach(e=>e.remove());const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);clearTimeout(toastTimer);toastTimer=setTimeout(()=>d.remove(),2200)}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state));showToast('セーブしました 💾')}
function load(){const raw=localStorage.getItem(SAVE_KEY);if(!raw)return;state=JSON.parse(raw);state.screen='game';state.pendingEvent=null;state.modalMemberId=null;state.liveRun=null;render()}
function reset(){if(confirm('現在のプレイを終了してタイトルへ戻りますか？')){state=freshState();render()}}
function escapeHTML(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function titleScreen(){const has=!!localStorage.getItem(SAVE_KEY);return `<div class="hero"><div class="hero-card"><div class="eyebrow">IDOL MANAGEMENT SIMULATOR</div><h1 class="brand-title">IDOL DYNASTY</h1><p class="muted">v0.7 推し育成・アイドル人生アップデート</p><div class="grid grid2" style="margin-top:24px"><div class="card soft"><h2>あなたが作るのは、数字じゃない。</h2><p>候補生を選び、センターを決め、曲と衣装を作り、ライブを成功させる。ライバルに負け、推しが覚醒し、いつか伝説になる。</p><div class="stack"><button onclick="newGame()">新しい事務所を始める</button>${has?'<button class="secondary" onclick="load()">続きから</button>':''}</div></div><div class="card"><div class="eyebrow">v0.7 NEW LOOP</div><div class="mini-list" style="margin-top:12px"><div class="mini-item">🎯 3か月目標と本番</div><div class="mini-item">👑 選抜・センターのドラマ</div><div class="mini-item">🎵 楽曲ジャケット制作</div><div class="mini-item">🎤 ライブ本番イベント</div><div class="mini-item">💬 メンバー個人ストーリー</div><div class="mini-item">📸 アー写・SNS・ポスター</div></div></div></div></div></div>`}
function newGame(){state=freshState();setup={agency:'LUMIERE PRODUCTION',group:'ASTERIA',concept:'seiso',logoColor:'#6bcffa',logoMark:'✦',outfit:'制服'};selectSet=new Set();state.screen='setup';render()}
function setupScreen(){return `<div class="hero"><div class="hero-card"><div class="eyebrow">STEP 1 / PRODUCE</div><h1>事務所とグループを作る</h1><div class="grid grid2"><div><div class="formrow"><label>事務所名</label><input value="${escapeHTML(setup.agency)}" oninput="setup.agency=this.value"></div><div class="formrow"><label>グループ名</label><input value="${escapeHTML(setup.group)}" oninput="setup.group=this.value"></div><div class="formrow"><label>コンセプト</label><div class="choice-row">${CONCEPTS.map(c=>`<div class="choice ${setup.concept===c[0]?'active':''}" onclick="setup.concept='${c[0]}';render()">${c[1]}</div>`).join('')}</div></div><div class="formrow"><label>デビュー衣装</label><select onchange="setup.outfit=this.value">${OUTFITS.map(o=>`<option ${setup.outfit===o[0]?'selected':''}>${o[0]}</option>`).join('')}</select></div><div class="formrow"><label>ロゴカラー</label><div class="choice-row">${COLORS.slice(0,6).map(c=>`<div class="choice ${setup.logoColor===c[1]?'active':''}" onclick="setup.logoColor='${c[1]}';render()"><span class="color-dot" style="background:${c[1]}"></span> ${c[0]}</div>`).join('')}</div></div><div class="formrow"><label>ロゴマーク</label><div class="choice-row">${['✦','♥','✿','♛','◆','☾'].map(x=>`<div class="choice ${setup.logoMark===x?'active':''}" onclick="setup.logoMark='${x}';render()">${x}</div>`).join('')}</div></div><button onclick="beginAudition()">オーディションを開催する</button></div><div>${setupPreview()}</div></div></div></div>`}
function setupPreview(){const c=CONCEPTS.find(x=>x[0]===setup.concept);return `<div class="group-visual"><div class="group-wordmark" style="color:${setup.logoColor}">${setup.logoMark} ${escapeHTML(setup.group||'GROUP NAME')}</div><div class="group-sub">${escapeHTML(setup.agency||'AGENCY')} / ${c?.[1]}</div><div style="position:absolute;left:24px;bottom:24px" class="badge pink">デビュー衣装：${setup.outfit}</div><span class="spark" style="right:16%;top:23%">✦</span><span class="spark" style="right:28%;top:40%">✧</span></div>`}
function beginAudition(){if(!setup.agency.trim()||!setup.group.trim()){alert('事務所名とグループ名を入力してください');return}state.agency=setup.agency.trim();state.group=setup.group.trim();state.concept=setup.concept;state.logoColor=setup.logoColor;state.logoMark=setup.logoMark;state.outfit=setup.outfit;state.members=[];for(let i=0;i<8;i++)state.members.push(freshMember(i));state.screen='audition';render()}
function auditionScreen(){return `<div class="wrap"><div class="topbar"><div><div class="eyebrow">STEP 2 / AUDITION</div><h1>デビューメンバーを選ぶ</h1><div class="muted">写真と個性を見て5人を選択。数値だけでなく「この子を売りたい」で選んでいい。</div></div><div class="badge">${selectSet.size}/5人</div></div><div class="audition-grid">${state.members.map(m=>candidateCard(m)).join('')}</div><div class="card" style="position:sticky;bottom:8px;margin-top:14px;z-index:10"><div class="split"><div><strong>${selectSet.size===5?'この5人でデビューする？':'5人選んでください'}</strong><div class="muted">選ばなかった候補生は今回は不合格になります。</div></div><button ${selectSet.size!==5?'disabled':''} onclick="finishAudition()">デビュー決定</button></div></div></div>`}
function candidateCard(m){const sel=selectSet.has(m.id);return `<div class="candidate ${sel?'selected-ring':''}" onclick="toggleCandidate('${m.id}')"><img src="${m.portrait}"><div class="body"><div class="split"><strong>${m.name}</strong><span class="color-dot" style="background:${m.color}"></span></div><div class="muted">${m.age}歳 / ${m.trait}</div><div class="stack" style="margin-top:8px"><span class="badge">スター ${m.star}</span><span class="badge pink">成長 ${m.potential}</span></div><div style="margin-top:9px;font-size:12px">${m.stats.visual>=75?'📸 画面映え ':''}${m.stats.dance>=72?'💃 ダンスエース ':''}${m.stats.sns>=72?'📱 SNS強者 ':''}${m.stats.vocal>=72?'🎙 歌唱メン ':''}</div></div></div>`}
function toggleCandidate(id){if(selectSet.has(id))selectSet.delete(id);else if(selectSet.size<5)selectSet.add(id);render()}
function finishAudition(){state.members=state.members.filter(m=>selectSet.has(m.id));state.centerId=state.members.slice().sort((a,b)=>b.star-a.star)[0].id;state.selectedIds=state.members.map(m=>m.id);state.fans=120;state.cash-=180000;state.history.push(`1年目1月 ${state.group} 結成。デビューメンバー5名を選出。`);state.news.unshift(`${state.group}、結成メンバーを発表。`);createDebutSong();setObjective(true);state.screen='game';render()}
function createDebutSong(){const c=center();state.songs.push({id:'s'+Date.now(),title:'はじまりの合図',style:'cute',centerId:c.id,quality:54,released:true,month:1,year:1});state.activeSongId=state.songs[0].id}
function setObjective(first=false){const p=power();const options=[];if(first||state.objectiveCount===0)options.push({type:'live',icon:'🎤',title:'初ワンマンを満員にする',desc:'3か月後の100人ワンマンを成功させる',target:100,progress:0,rewardFans:800,rewardCash:250000,deadline:3,venueId:'100'});else{options.push({type:'fans',icon:'📣',title:`ファン${Math.max(1000,Math.ceil((state.fans+800)/500)*500).toLocaleString()}人へ`,desc:'SNS・ライブ・特典会でファンベースを広げる',target:Math.max(1000,Math.ceil((state.fans+800)/500)*500),progress:state.fans,rewardFans:300,rewardCash:180000,deadline:3});options.push({type:'power',icon:'⚔️',title:`総合力${Math.min(95,p+7)}を突破`,desc:'育成と作品制作でグループ力を伸ばす',target:Math.min(95,p+7),progress:p,rewardFans:500,rewardCash:200000,deadline:3});options.push({type:'song',icon:'🎵',title:'新曲をヒットさせる',desc:'新曲を制作し、品質70以上でリリースする',target:70,progress:Math.max(0,...state.songs.map(s=>s.quality||0)),rewardFans:700,rewardCash:220000,deadline:3});}state.objective={...pick(options),startAbs:(state.year-1)*12+state.month};state.objectiveCount++}
function monthsSinceGoal(){return (state.year-1)*12+state.month-state.objective.startAbs}
function objectiveProgress(){if(!state.objective)return 0;const o=state.objective;if(o.type==='fans')return state.fans;if(o.type==='power')return power();if(o.type==='song')return Math.max(0,...state.songs.map(s=>s.quality||0));if(o.type==='live')return state.lastMonth?.liveAttendance||0;return 0}
function goalComplete(){const o=state.objective;return objectiveProgress()>=o.target}
function objectiveCard(){const o=state.objective,prog=objectiveProgress(),pct=clamp(prog/o.target*100,0,100),left=Math.max(0,o.deadline-monthsSinceGoal());return `<div class="card goal-card"><div class="goal-head"><div class="goal-icon">${o.icon}</div><div><div class="eyebrow">CURRENT MISSION / あと${left}か月</div><div class="goal-title">${o.title}</div><div class="muted">${o.desc}</div></div><div class="badge gold">報酬 +${o.rewardFans} fans / ${money(o.rewardCash)}</div></div><div class="split" style="margin-top:12px"><strong>${prog.toLocaleString()} / ${o.target.toLocaleString()}</strong><span class="muted">${Math.round(pct)}%</span></div><div class="progress gold" style="margin-top:7px"><div style="width:${pct}%"></div></div>${o.type==='live'&&left===0?'<div style="margin-top:12px"><button class="pink" onclick="quickGoalLive()">初ワンマン本番へ</button></div>':''}</div>`}
function gameShell(){return `<div class="wrap">${header()}${nav()}${tabContent()}</div>`}
function header(){return `<div class="topbar"><div><div class="eyebrow">${escapeHTML(state.agency)} / ${state.year}年目 ${state.month}月</div><h1><span style="color:${state.logoColor}">${state.logoMark}</span> ${escapeHTML(state.group)}</h1><div class="stack"><span class="badge">Tier ${tier()}</span><span class="badge pink">総合力 ${power()}</span><span class="badge green">ファン ${state.fans.toLocaleString()}</span></div></div><div class="stack"><button class="secondary" onclick="save()">保存</button><button class="secondary" onclick="reset()">タイトル</button></div></div>`}
function nav(){const tabs=[['home','ホーム'],['members','メンバー'],['creative','作品制作'],['live','ライブ'],['rivals','勢力図'],['company','事務所']];return `<div class="nav">${tabs.map(t=>`<button class="${state.tab===t[0]?'active':'secondary'}" onclick="setTab('${t[0]}')">${t[1]}</button>`).join('')}</div>`}
function setTab(t){state.tab=t;state.modalMemberId=null;render()}
function tabContent(){if(state.tab==='members')return membersTab();if(state.tab==='creative')return creativeTab();if(state.tab==='live')return liveTab();if(state.tab==='rivals')return rivalsTab();if(state.tab==='company')return companyTab();return homeTab()}
function homeTab(){return `${objectiveCard()}<div class="grid grid2" style="margin-top:14px"><div>${groupVisual()}</div><div class="card"><div class="eyebrow">MONTHLY PRODUCE</div><h2>今月、何に賭ける？</h2><div class="grid grid2">${ACTIONS.map(actionCard).join('')}</div><div class="split" style="margin-top:14px"><div class="muted">選択した行動を実行すると1か月進みます。</div><button ${!state.selectedAction?'disabled':''} onclick="executeMonth()">今月を進める</button></div></div></div><div class="grid grid2" style="margin-top:14px"><div class="card"><div class="section-title" style="margin-top:0"><h2>メンバーの今</h2><button class="secondary" onclick="setTab('members')">全員を見る</button></div><div class="grid grid2">${activeMembers().slice(0,4).map(memberMini).join('')}</div></div><div class="card"><div class="section-title" style="margin-top:0"><h2>業界ニュース</h2><span class="muted">ライバルも毎月動く</span></div><div class="timeline">${state.news.slice(0,7).map((n,i)=>`<div class="timeline-item"><div class="timeline-time">${i?'RECENT':'NOW'}</div><div>${escapeHTML(n)}</div></div>`).join('')||'<div class="muted">まだ大きなニュースはありません。</div>'}</div></div></div>`}
function actionCard(a){return `<div class="card action-card ${state.selectedAction===a.id?'selected':''}" onclick="state.selectedAction='${a.id}';render()"><div class="action-icon">${a.icon}</div><strong>${a.name}</strong><div class="muted" style="font-size:12px;margin-top:4px">${a.desc}</div><div class="impact">${a.impact}</div><div class="cost">費用 ${money(a.cost)}</div></div>`}
function groupVisual(){const ms=[...activeMembers()].sort((a,b)=>(a.id===state.centerId?-1:b.id===state.centerId?1:0));return `<div class="group-visual"><div class="group-wordmark" style="color:${state.logoColor}">${state.logoMark} ${escapeHTML(state.group)}</div><div class="group-sub">${state.outfit}衣装 / ${CONCEPTS.find(c=>c[0]===state.concept)?.[1]}</div><div class="group-lineup">${ms.map(m=>`<div class="group-person ${m.id===state.centerId?'center':''}"><img src="${m.portrait}"></div>`).join('')}</div><span class="spark" style="right:14%;top:18%">✦</span><span class="spark" style="right:30%;top:30%">✧</span></div>`}
function memberMini(m){return `<div class="mini-item" onclick="openMember('${m.id}')" style="cursor:pointer"><div class="split"><strong><span class="color-dot" style="background:${m.color}"></span> ${m.name}</strong>${m.id===state.centerId?'<span class="badge gold">CENTER</span>':''}</div><div class="muted">人気 ${m.popularity.toLocaleString()} / 気分 ${m.mood} / 疲労 ${m.fatigue}</div></div>`}
function membersTab(){return `<div class="section-title"><div><div class="eyebrow">MEMBER PRODUCE</div><h2>推しを育てる</h2></div><div class="muted">センターを選ぶと他メンバーの感情にも影響します。</div></div><div class="member-grid">${activeMembers().map(memberCard).join('')}</div><div class="card" style="margin-top:14px"><div class="split"><div><strong>次シングルのセンター</strong><div class="muted">今のセンター：${center()?.name}</div></div><select style="width:auto" onchange="changeCenter(this.value)">${activeMembers().map(m=>`<option value="${m.id}" ${m.id===state.centerId?'selected':''}>${m.name}</option>`).join('')}</select></div></div>`}
function visualStage(m){return m.popularity>=3500?'star':m.popularity>=1000?'stage':''}
function memberCard(m){return `<div class="member-card" onclick="openMember('${m.id}')">${m.id===state.centerId?'<div class="center-crown">👑 CENTER</div>':''}<div class="portrait-frame ${visualStage(m)}"><img src="${m.portrait}"></div><div class="body"><div class="split"><strong><span class="color-dot" style="background:${m.color}"></span> ${m.name}</strong><span class="badge">${m.trait}</span></div><div class="muted">${m.age}歳 / ${m.colorName}</div><div class="stack" style="margin-top:9px"><span class="badge pink">人気 ${m.popularity}</span><span class="badge">スター ${m.star}</span></div></div></div>`}
function changeCenter(id){if(id===state.centerId)return;const old=center();const next=state.members.find(m=>m.id===id);state.centerId=id;next.mood=clamp(next.mood+8,0,100);next.ambition=clamp(next.ambition+5,0,100);if(old){old.mood=clamp(old.mood-4,0,100);old.storyLog.unshift('センター交代を経験した。')}state.news.unshift(`${state.group}、次作センターに${next.name}を指名。ファンの間で議論が広がる。`);state.history.push(`${state.year}年目${state.month}月 センターを${next.name}へ変更。`);render()}
function openMember(id){state.modalMemberId=id;render()}
function closeMember(){state.modalMemberId=null;document.querySelectorAll('.modal-bg').forEach(e=>e.remove())}
function memberModal(id){const m=state.members.find(x=>x.id===id);if(!m)return '';return `<div class="modal-bg" onclick="if(event.target===this)closeMember()"><div class="modal"><div class="split"><div><div class="eyebrow">IDOL PROFILE CARD</div><h2 style="margin:3px 0"><span class="color-dot" style="background:${m.color}"></span> ${m.name}</h2><div class="muted">${m.age}歳 / ${m.trait} / メンバーカラー ${m.colorName}</div></div><button class="secondary" onclick="closeMember()">閉じる</button></div><div class="profile-layout" style="margin-top:14px"><div><div class="portrait-frame ${visualStage(m)}"><img src="${m.portrait}"></div><div class="card soft" style="margin-top:10px"><div class="split"><strong>個人人気</strong><span>${m.popularity.toLocaleString()}</span></div><div class="split"><span>気分</span><span>${m.mood}</span></div><div class="split"><span>疲労</span><span>${m.fatigue}</span></div><div class="split"><span>野心</span><span>${m.ambition}</span></div><div class="split"><span>信頼</span><span>${m.bond}</span></div></div><button style="width:100%;margin-top:10px" onclick="talkMember('${m.id}')">1on1で話す</button></div><div><div class="card"><h3 style="margin-top:0">能力</h3>${Object.entries(m.stats).map(([k,v])=>statRow({vocal:'歌唱',dance:'ダンス',visual:'ビジュアル',talk:'トーク',sns:'SNS',stage:'ステージ'}[k],v)).join('')}${statRow('スター性',m.star)}${statRow('ポテンシャル',m.potential)}</div><div class="card" style="margin-top:12px"><h3 style="margin-top:0">この子の物語</h3>${m.storyLog.slice(0,6).map(x=>`<div class="mini-item">${escapeHTML(x)}</div>`).join('')||'<div class="muted">まだ大きな出来事はない。これから物語が始まる。</div>'}</div></div></div></div></div>`}
function statRow(n,v){return `<div class="statrow"><span>${n}</span><div class="progress"><div style="width:${v}%"></div></div><strong>${v}</strong></div>`}
function talkMember(id){const m=state.members.find(x=>x.id===id);const lines=m.ambition>70?[`「次の曲、センター本気で狙いたいです。」`,`「もっと大きいステージに行けると思ってます。」`]:m.fatigue>65?[`「ちょっと最近、身体が重いかも…。」`,`「休んだ方がいいって分かってるんですけど。」`]:[`「今のグループ、もっと好きになってきました。」`,`「次のライブ、絶対成功させたいです。」`];state.pendingEvent={type:'talk',memberId:id,title:`${m.name}との1on1`,text:pick(lines),options:['背中を押す','現実的に話す','休ませる']};render()}
function creativeTab(){const latest=state.songs[state.songs.length-1];return `<div class="section-title"><div><div class="eyebrow">CREATIVE STUDIO</div><h2>作品を作る</h2></div><div class="muted">タイトル・センター・世界観が「作品」として残る。</div></div><div class="grid grid2"><div class="card"><h3>新曲制作</h3><div class="formrow"><label>曲名</label><input id="songTitle" value="${pick(SONG_TITLES)}"></div><div class="formrow"><label>ジャケット世界観</label><select id="songStyle"><option value="cute">王道ポップ</option><option value="dreamy">儚い</option><option value="cool">クール</option><option value="rock">ロック</option></select></div><div class="formrow"><label>制作予算</label><select id="songBudget"><option value="250000">25万円 / インディーズ</option><option value="600000">60万円 / 本格制作</option><option value="1200000">120万円 / 勝負曲</option></select></div><button onclick="produceSong()">この曲を作る</button><div class="help" style="margin-top:12px">制作費を上げるほど品質の上振れが大きくなります。センターのスター性とクリエイティブスタッフも影響。</div></div><div>${latest?jacket(latest):'<div class="card"><p class="muted">まだ楽曲がありません。</p></div>'}</div></div><div class="section-title"><h2>ディスコグラフィー</h2></div><div class="grid grid3">${state.songs.slice().reverse().map(s=>`<div>${jacket(s)}<div class="card" style="margin-top:8px"><div class="split"><strong>${escapeHTML(s.title)}</strong><span class="badge ${s.quality>=75?'gold':''}">品質 ${s.quality}</span></div><div class="muted">CENTER ${state.members.find(m=>m.id===s.centerId)?.name||'-'} / ${s.year}年目${s.month}月</div><button class="secondary" style="margin-top:9px" onclick="state.activeSongId='${s.id}';render()">表題曲にする</button></div></div>`).join('')}</div>`}
function jacket(s){const m=state.members.find(x=>x.id===s.centerId)||center();return `<div class="jacket ${s.style}"><img src="${m?.portrait}"><div class="meta">${state.logoMark} ${escapeHTML(state.group)}</div><div class="title">${escapeHTML(s.title)}</div></div>`}
function produceSong(){const title=$('#songTitle').value.trim()||pick(SONG_TITLES),style=$('#songStyle').value,budget=Number($('#songBudget').value);if(state.cash<budget){alert('資金が足りません');return}state.cash-=budget;const c=center();const base=48+Math.round(budget/60000)+Math.round(c.star*.1)+rand(-5,8)+(state.staff.creative?8:0);const q=clamp(base,40,96);const song={id:'s'+Date.now(),title,style,centerId:c.id,quality:q,released:true,year:state.year,month:state.month};state.songs.push(song);state.activeSongId=song.id;state.brand=clamp(state.brand+Math.round(q/22),0,100);state.news.unshift(`${state.group}が新曲「${title}」を発表。${q>=75?'ジャケットと楽曲の完成度が高いと話題。':'ファンの反応が集まり始める。'}`);state.history.push(`${state.year}年目${state.month}月 「${title}」リリース（品質${q}）。`);render()}
function liveTab(){const v=VENUES.find(x=>x.id===state.livePlan.venueId),latestSong=state.songs.find(s=>s.id===state.activeSongId);return `<div class="section-title"><div><div class="eyebrow">LIVE PRODUCTION</div><h2>ライブを作る</h2></div><div class="muted">会場選びからポスター、本番の判断まで。</div></div><div class="grid grid2"><div class="card"><div class="formrow"><label>会場</label><select onchange="state.livePlan.venueId=this.value;render()">${VENUES.map(x=>`<option value="${x.id}" ${x.id===v.id?'selected':''} ${power()<x.power?'disabled':''}>${x.name} / ${x.cap.toLocaleString()}人 / ${money(x.cost)}</option>`).join('')}</select></div><div class="mini-list"><div class="mini-item"><div class="split"><span>予想動員</span><strong>${estimateAttendance(v).toLocaleString()} / ${v.cap.toLocaleString()}</strong></div></div><div class="mini-item"><div class="split"><span>現在のライブ力</span><strong>${state.livePower}</strong></div></div><div class="mini-item"><div class="split"><span>表題曲</span><strong>${escapeHTML(latestSong?.title||'未設定')}</strong></div></div></div><button class="pink" style="width:100%;margin-top:12px" onclick="startLive()">ライブ本番へ</button></div><div>${livePoster(v)}</div></div><div class="section-title"><h2>ライブ履歴</h2></div><div class="timeline">${state.history.filter(x=>x.includes('LIVE')).slice(-8).reverse().map(x=>`<div class="timeline-item"><div class="timeline-time">LIVE</div><div>${escapeHTML(x)}</div></div>`).join('')||'<div class="muted">まだライブ履歴はありません。</div>'}</div>`}
function livePoster(v){const c=center();const est=estimateAttendance(v);return `<div class="poster"><img src="${c?.portrait}"><div class="poster-top"><div class="eyebrow" style="color:#fff">${state.year} YEAR ${state.month} MONTH</div><h3>${escapeHTML(state.group)}<br>ONE MAN LIVE</h3><div>${v.name}</div></div>${est>=v.cap?'<div class="sold">SOLD OUT?</div>':''}<div class="poster-bottom"><div class="split"><strong>CENTER ${c?.name}</strong><span>${state.outfit}衣装</span></div></div></div>`}
function estimateAttendance(v){const song=state.songs.find(s=>s.id===state.activeSongId);const draw=state.fans*(.13+state.trust/500)+state.buzz*7+state.livePower*4+(song?.quality||40)*2;return clamp(Math.round(draw*rand(88,112)/100),10,v.cap)}
function startLive(){const v=VENUES.find(x=>x.id===state.livePlan.venueId);if(state.cash<v.cost){alert('ライブ開催費が足りません');return}state.cash-=v.cost;const att=estimateAttendance(v);const event=pick([{title:'センターが開演直前に緊張',text:`${center().name}の手が震えている。どう声をかける？`,options:['「楽しんでこい」','「絶対成功させよう」','黙って背中を叩く'],bonus:[5,3,4]},{title:'音響トラブル発生',text:'2曲目直前、イヤモニにノイズ。どうする？',options:['MCでつなぐ','そのまま突入','一度止める'],bonus:[6,-2,2]},{title:'アンコールが止まらない',text:'予定外のWアンコール。メンバーは疲れている。',options:['新曲をもう一度','MCだけで応える','予定通り終了'],bonus:[7,3,0]}]);state.liveRun={venue:v,attendance:att,event,choice:null,score:null};state.screen='liveRun';render()}
function liveRunScreen(){const r=state.liveRun;if(r.score!=null)return liveResult();return `<div class="wrap"><div class="live-stage"><div class="stage-light l1"></div><div class="stage-light l2"></div><div class="stage-title"><div class="eyebrow" style="color:#dff8ff">NOW ON STAGE</div><h1>${escapeHTML(state.group)} ONE MAN LIVE</h1><div>${r.attendance.toLocaleString()} / ${r.venue.cap.toLocaleString()} 来場</div></div><div class="stage-lineup">${activeMembers().map(m=>`<div class="stage-person ${m.id===state.centerId?'center':''}"><img src="${m.portrait}"></div>`).join('')}</div><div class="crowd"></div></div><div class="live-event"><div class="eyebrow">LIVE EVENT</div><h2>${r.event.title}</h2><p>${r.event.text}</p><div class="choice-row">${r.event.options.map((o,i)=>`<button class="${i?'secondary':''}" onclick="resolveLive(${i})">${o}</button>`).join('')}</div></div></div>`}
function resolveLive(i){const r=state.liveRun;r.choice=i;const sell=r.attendance/r.venue.cap*100;const skill=avg(activeMembers().map(m=>m.stats.stage))*0.32+state.livePower*.38+(state.songs.find(s=>s.id===state.activeSongId)?.quality||45)*.22+state.trust*.08;const score=clamp(Math.round(skill*.7+sell*.3+r.event.bonus[i]+rand(-4,5)),35,100);r.score=score;const ticket=r.attendance*r.venue.ticket;state.cash+=ticket;const gain=Math.round(r.attendance*(score/100)*(.8+state.brand/180));state.fans+=gain;state.livePower=clamp(state.livePower+Math.round(score/18),0,100);state.buzz=clamp(state.buzz+Math.round(score/14),0,100);activeMembers().forEach(m=>{m.fatigue=clamp(m.fatigue+rand(10,18),0,100);m.popularity+=Math.round(gain*(m.id===state.centerId ? .22 : .13));m.mood=clamp(m.mood+(score>=80?6:score<55?-6:2),0,100)});state.lastMonth={...(state.lastMonth||{}),liveAttendance:r.attendance};state.news.unshift(`${state.group} ${r.venue.name}公演、${r.attendance}人動員。ライブ評価${score}点。`);state.history.push(`${state.year}年目${state.month}月 LIVE ${r.venue.name} ${r.attendance}/${r.venue.cap}人 評価${score}。`);render()}
function liveResult(){const r=state.liveRun;return `<div class="hero"><div class="hero-card"><div class="eyebrow">LIVE RESULT</div><div class="live-score" style="color:#4bbde9">${r.score}</div><h1>${r.score>=90?'伝説級の夜になった。':r.score>=75?'次につながる成功。':r.score>=55?'課題を残しつつ完走。':'悔しさが残る夜。'}</h1><div class="kpis"><div class="kpi"><div class="label">動員</div><div class="value">${r.attendance}/${r.venue.cap}</div></div><div class="kpi"><div class="label">ライブ評価</div><div class="value">${r.score}</div></div><div class="kpi"><div class="label">ライブ力</div><div class="value">${state.livePower}</div></div><div class="kpi"><div class="label">ファン</div><div class="value">${state.fans.toLocaleString()}</div></div><div class="kpi"><div class="label">総合力</div><div class="value">${power()}</div></div></div><button style="margin-top:20px" onclick="finishLiveRun()">ゲームに戻る</button></div></div>`}
function finishLiveRun(){state.liveRun=null;state.screen='game';checkGoal();render()}
function quickGoalLive(){state.livePlan.venueId='100';startLive()}
function rivalsTab(){updateRivalRanks(false);const rows=[...state.rivals.map(r=>({...r,self:false})),{name:state.group,power:power(),growth:state.lastMonth?.powerGain||0,fans:state.fans,self:true}].sort((a,b)=>b.power-a.power);return `<div class="section-title"><div><div class="eyebrow">IDOL POWER MAP</div><h2>今のアイドル戦国時代</h2></div><div class="muted">毎月ライバルも成長する。</div></div><div class="card">${rows.map((r,i)=>`<div class="rankrow ${r.self?'self':''}"><strong>#${i+1}</strong><div><strong>${escapeHTML(r.name)}${r.self?' ★':''}</strong><div class="muted">fans ${r.fans.toLocaleString()}</div></div><strong>${r.power}</strong><span>${r.growth>=0?'+':''}${r.growth}</span><span>${tier(r.power)}</span></div>`).join('')}</div><div class="section-title"><h2>ライバルニュース</h2></div><div class="grid grid3">${state.rivals.slice(0,3).map(r=>`<div class="card"><div class="eyebrow">RIVAL</div><h3>${r.name}</h3><div class="kpi"><div class="label">総合力</div><div class="value">${r.power}</div></div><p class="muted">${r.growth>=5?'大型施策が当たり急成長中。':r.growth<0?'伸び悩み。立て直しを図っている。':'着実にファンを増やしている。'}</p></div>`).join('')}</div>`}
function companyTab(){const staffDefs=[['manager','現場マネージャー',180000,'疲労を軽減'],['trainer','育成ディレクター',220000,'レッスン強化'],['sns','SNSプロデューサー',200000,'SNS施策強化'],['creative','クリエイティブD',260000,'楽曲品質強化']];return `<div class="section-title"><div><div class="eyebrow">AGENCY MANAGEMENT</div><h2>${escapeHTML(state.agency)}</h2></div><span class="badge">現金 ${money(state.cash)}</span></div><div class="grid grid2"><div class="card"><h3>スタッフ</h3><div class="mini-list">${staffDefs.map(s=>`<div class="mini-item"><div class="split"><div><strong>${s[1]}</strong><div class="muted">${s[3]} / 月${money(s[2])}</div></div>${state.staff[s[0]]?'<span class="badge green">雇用中</span>':`<button class="secondary" onclick="hireStaff('${s[0]}',${s[2]})">雇う</button>`}</div></div>`).join('')}</div></div><div class="card"><h3>現在の事務所</h3><div class="kpis" style="grid-template-columns:repeat(2,1fr)"><div class="kpi"><div class="label">ブランド</div><div class="value">${state.brand}</div></div><div class="kpi"><div class="label">ファン信頼</div><div class="value">${state.trust}</div></div><div class="kpi"><div class="label">話題性</div><div class="value">${state.buzz}</div></div><div class="kpi"><div class="label">固定費</div><div class="value" style="font-size:18px">${money(monthlyCost())}</div></div></div></div></div><div class="section-title"><h2>事務所の歴史</h2></div><div class="timeline">${state.history.slice().reverse().map(x=>`<div class="timeline-item"><div class="timeline-time">HISTORY</div><div>${escapeHTML(x)}</div></div>`).join('')}</div>`}
function hireStaff(id,salary){if(state.cash<salary){alert('初月給与を払える資金がありません');return}state.staff[id]=true;state.cash-=salary;state.news.unshift(`${state.agency}が新スタッフを採用。制作体制を強化。`);render()}
function monthlyCost(){const salaries={manager:180000,trainer:220000,sns:200000,creative:260000};return state.monthlyFixed+Object.entries(state.staff).filter(x=>x[1]).reduce((s,[k])=>s+salaries[k],0)}
function executeMonth(){const a=ACTIONS.find(x=>x.id===state.selectedAction);if(!a)return;if(state.cash<a.cost){alert('資金が足りません');return}const beforeFans=state.fans,beforePower=power();state.cash-=a.cost;let headline='';const ms=activeMembers();if(a.id==='lesson'){ms.forEach(m=>{const b=state.staff.trainer?rand(4,8):rand(2,6);m.stats.vocal=clamp(m.stats.vocal+rand(1,b),0,100);m.stats.dance=clamp(m.stats.dance+rand(1,b),0,100);m.stats.stage=clamp(m.stats.stage+rand(1,b),0,100);m.fatigue=clamp(m.fatigue+rand(7,13),0,100)});headline='レッスン漬けの1か月。少しずつステージが締まってきた。'}
 if(a.id==='sns'){const c=pick(ms);const viral=rand(180,680)+(state.staff.sns?420:0)+Math.round(c.stats.sns*5);state.fans+=viral;state.buzz=clamp(state.buzz+rand(4,10),0,100);c.popularity+=Math.round(viral*.38);c.fatigue=clamp(c.fatigue+6,0,100);createSNSPost(c,viral);headline=`${c.name}の投稿が伸び、SNSで新規ファンが増えた。`}
 if(a.id==='street'){const gain=rand(120,390)+state.livePower*3;state.fans+=gain;state.livePower=clamp(state.livePower+rand(2,5),0,100);ms.forEach(m=>{m.stats.stage=clamp(m.stats.stage+rand(1,3),0,100);m.fatigue=clamp(m.fatigue+rand(7,12),0,100)});headline='小さな現場を重ね、熱量の高いファンがついた。'}
 if(a.id==='fan'){const sales=rand(80000,220000)+Math.round(state.fans*80);state.cash+=sales;state.trust=clamp(state.trust+rand(3,7),0,100);state.fans+=rand(60,180);ms.forEach(m=>m.mood=clamp(m.mood+3,0,100));headline='特典会でファンとの距離が縮まった。'}
 if(a.id==='media'){const hit=Math.random()<(.28+state.brand/180);if(hit){const gain=rand(350,900);state.fans+=gain;state.cash+=rand(120000,450000);state.brand=clamp(state.brand+rand(3,6),0,100);headline='メディア案件を獲得。グループの名前が外へ広がった。'}else{state.brand=clamp(state.brand+1,0,100);headline='営業を重ねた。大きな結果はまだだが、業界内の接点が増えた。'}}
 if(a.id==='rest'){ms.forEach(m=>{m.fatigue=clamp(m.fatigue-rand(14,26),0,100);m.mood=clamp(m.mood+rand(5,10),0,100)});headline='休養と制作会議。次に向けてチームの空気が整った。'}
 applyFatigueMood();state.cash-=monthlyCost();updateRivalRanks(true);maybeStoryEvent();advanceMonth();const afterPower=power();state.lastMonth={headline,fanGain:state.fans-beforeFans,powerGain:afterPower-beforePower};state.news.unshift(`${state.group}: ${headline}`);state.selectedAction=null;checkGoal();maybeYearEvent();render()}
function applyFatigueMood(){activeMembers().forEach(m=>{if(state.staff.manager)m.fatigue=clamp(m.fatigue-3,0,100);if(m.fatigue>80){m.mood=clamp(m.mood-rand(4,9),0,100);m.stats.stage=clamp(m.stats.stage-1,0,100)}if(m.mood>80&&Math.random()<.18){const key=pick(['vocal','dance','visual','talk','sns','stage']);m.stats[key]=clamp(m.stats[key]+rand(2,5),0,100);m.storyLog.unshift('調子の良い時期に一段階成長した。')}})}
function createSNSPost(m,gain){state.snsPosts.unshift({id:Date.now(),memberId:m.id,likes:gain*rand(15,35),text:pick(['今日も練習してきたよ🩵','新衣装、どう？','ライブ来てくれてありがとう！','オフショット📸 また会おうね']),year:state.year,month:state.month});state.snsPosts=state.snsPosts.slice(0,12)}
function updateRivalRanks(doMove=true){if(!doMove)return;state.rivals.forEach(r=>{r.growth=rand(-2,7);r.power=clamp(r.power+Math.round(r.growth/2),8,98);r.fans=Math.round(r.fans*(1+r.growth/100));if(r.growth>=6&&Math.random()<.35)state.news.unshift(`${r.name}が大型ライブを発表。勢力図が動く。`)})}
function maybeStoryEvent(){if(state.pendingEvent||Math.random()>.32)return;const m=pick(activeMembers());if(!m)return;if(m.ambition>72){state.pendingEvent={type:'ambition',memberId:m.id,title:`${m.name}がセンターを直訴`,text:'「次の曲、私をセンターにしてください。絶対に結果を出します。」',options:['任せる','実力で勝ち取れ','今はまだ早い']}}else if(m.fatigue>65){state.pendingEvent={type:'fatigue',memberId:m.id,title:`${m.name}が弱音を見せる`,text:'「最近ちょっと、追いつけてない気がして…。」',options:['休ませる','一緒に練習する','厳しく鼓舞する']}}else{state.pendingEvent={type:'bond',memberId:m.id,title:`${m.name}から相談`,text:'「もっと自分の強みを作りたいです。プロデューサーは私の何を伸ばしたい？」',options:['歌','ダンス','SNS']}}}
function eventModal(e){return `<div class="modal-bg"><div class="modal"><div class="eyebrow">MEMBER STORY EVENT</div><h2>${escapeHTML(e.title)}</h2><p style="font-size:18px">${escapeHTML(e.text)}</p><div class="choice-row">${e.options.map((o,i)=>`<button class="${i?'secondary':''}" onclick="resolveEvent(${i})">${o}</button>`).join('')}</div></div></div>`}
function resolveEvent(i){document.querySelectorAll('.modal-bg').forEach(e=>e.remove());const e=state.pendingEvent;if(!e)return;const m=state.members.find(x=>x.id===e.memberId);if(e.type==='ambition'){if(i===0){state.centerId=m.id;m.mood=clamp(m.mood+12,0,100);m.bond=clamp(m.bond+8,0,100);m.storyLog.unshift('自ら直訴し、センターの座をつかんだ。');state.news.unshift(`${m.name}がセンターへ。大胆な抜擢にファンが沸く。`)}if(i===1){m.potential=clamp(m.potential+4,0,100);m.mood=clamp(m.mood+3,0,100);m.storyLog.unshift('「実力で勝ち取れ」と言われ、火がついた。')}if(i===2){m.mood=clamp(m.mood-8,0,100);m.ambition=clamp(m.ambition+6,0,100);m.storyLog.unshift('センター希望を断られた。悔しさを胸に残した。')}}
 if(e.type==='fatigue'){if(i===0){m.fatigue=clamp(m.fatigue-28,0,100);m.bond+=8;m.storyLog.unshift('運営判断で休養し、立て直した。')}if(i===1){m.fatigue=clamp(m.fatigue-8,0,100);m.stats.stage+=3;m.bond+=5;m.storyLog.unshift('プロデューサーと練習し、自信を取り戻した。')}if(i===2){m.mood=clamp(m.mood-10,0,100);m.ambition+=5;m.storyLog.unshift('厳しい言葉を受け、踏ん張ることを選んだ。')}}
 if(e.type==='bond'||e.type==='talk'){const keys=['vocal','dance','sns'];const k=keys[Math.min(i,2)];m.stats[k]=clamp(m.stats[k]+rand(3,7),0,100);m.bond=clamp(m.bond+rand(2,6),0,100);m.storyLog.unshift(`${{vocal:'歌',dance:'ダンス',sns:'SNS'}[k]}を強みにする方針を決めた。`)}state.pendingEvent=null;render()}
function advanceMonth(){state.month++;if(state.month>12){state.month=1;state.year++}}
function checkGoal(){if(!state.objective)return;if(goalComplete()){const o=state.objective;state.fans+=o.rewardFans;state.cash+=o.rewardCash;state.brand=clamp(state.brand+4,0,100);state.history.push(`${state.year}年目${state.month}月 MISSION CLEAR「${o.title}」`);state.news.unshift(`MISSION CLEAR！ ${o.title}。グループが一段上へ。`);setObjective(false)}else if(monthsSinceGoal()>state.objective.deadline){state.trust=clamp(state.trust-4,0,100);state.news.unshift(`目標「${state.objective.title}」は未達。悔しさを次へ持ち越す。`);setObjective(false)}}
function maybeYearEvent(){if(state.month===1&&state.year>1){annualAwards();if(state.year===2&&!state.secondGen){state.news.unshift('2期生オーディションを開催できる時期になった。');state.secondGen=true}}}
function annualAwards(){const rank=[...state.rivals.map(r=>({name:r.name,p:r.power})),{name:state.group,p:power()}].sort((a,b)=>b.p-a.p);const pos=rank.findIndex(x=>x.name===state.group)+1;const text=`IDOL AWARDS ${state.year-1}: ${state.group} 総合${pos}位。`;state.awardLog.push(text);state.history.push(text);state.news.unshift(text)}
function socialSection(){return state.snsPosts.length?`<div class="section-title"><h2>SNSオフショット</h2></div><div class="grid grid3">${state.snsPosts.slice(0,3).map(p=>{const m=state.members.find(x=>x.id===p.memberId);return `<div class="social-card"><div class="social-photo"><img src="${m.portrait}"></div><div class="social-caption"><strong>${m.name}</strong><p>${escapeHTML(p.text)}</p><div class="like">♥ ${p.likes.toLocaleString()}</div></div></div>`}).join('')}</div>`:''}
function render(){document.querySelectorAll('.modal-bg,.toast').forEach(e=>e.remove());const app=$('#app');if(!state)state=freshState();if(state.screen==='title')app.innerHTML=titleScreen();else if(state.screen==='setup')app.innerHTML=setupScreen();else if(state.screen==='audition')app.innerHTML=auditionScreen();else if(state.screen==='liveRun')app.innerHTML=liveRunScreen();else app.innerHTML=gameShell()+(state.tab==='home'?socialSection():'');if(state.modalMemberId)document.body.insertAdjacentHTML('beforeend',memberModal(state.modalMemberId));if(state.pendingEvent)document.body.insertAdjacentHTML('beforeend',eventModal(state.pendingEvent))}
state=freshState();render();
